name: Keep Streamlit App Awake


on:
  schedule:

    - cron: '0 */10 * * *'

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App

        run: curl -f -s -o /dev/null "https://youngcha.streamlit.app"
